C:37:"PHPUnit\Runner\DefaultTestResultCache":1676:{a:2:{s:7:"defects";a:10:{s:7:"Warning";i:6;s:43:"Tests\Unit\RouterTest::it_registers_a_route";i:4;s:48:"Tests\Unit\RouterTest::it_registers_a_post_route";i:3;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #0";i:4;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #1";i:4;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #2";i:4;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #3";i:4;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #4";i:4;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #5";i:3;s:40:"Tests\Unit\RouterTest::it_resolves_route";i:4;}s:5:"times";a:13:{s:7:"Warning";d:0.006;s:43:"Tests\Unit\RouterTest::it_registers_a_route";d:0.017;s:47:"Tests\Unit\RouterTest::it_registers_a_get_route";d:0;s:48:"Tests\Unit\RouterTest::it_registers_a_post_route";d:0;s:66:"Tests\Unit\RouterTest::it_returns_no_routes_when_router_is_created";d:0;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #0";d:0.001;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #1";d:0;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #2";d:0;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #3";d:0;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #4";d:0;s:75:"Tests\Unit\RouterTest::it_throws_route_not_found_exception with data set #5";d:0;s:55:"Tests\Unit\RouterTest::it_resolves_route_from_a_closure";d:0;s:40:"Tests\Unit\RouterTest::it_resolves_route";d:0;}}}